package entity;
// Generated 2017/08/18 11:58:18 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

/**
 * Lesson01 generated by hbm2java
 */
@Entity
@Table(name="lesson01"
    ,catalog="test"
)
public class Lesson01  implements java.io.Serializable {


     private String userId;
     private String userName;
     private String password;

    public Lesson01() {
    }

    public Lesson01(String userId, String userName, String password) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
    }
   
     @Id 

    
    @Column(name="userID", unique=true, nullable=false, length=10)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }

    
    @Column(name="userName", nullable=false, length=10)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=10)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this,ToStringStyle.SHORT_PREFIX_STYLE);
    }


}


